# Generated by Django 4.1.7 on 2023-03-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_user_room_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_room',
            old_name='room_name',
            new_name='roomname',
        ),
    ]
