# Generated by Django 4.1.7 on 2023-03-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_room_name_user_room_roomname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_room',
            name='roomname',
        ),
    ]
